language: ruby
rvm:
  - 2.4.3
services:
  - postgresql
addons:
  postgresql: "9.6"
cache:
  directories:
    - vendor/bundle
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --path vendor/bundle --without production --jobs=3 --retry=1
before_script:
  - psql -c 'create database shim_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script:
  - bundle exec rake

